scheme: Mist

valine:
  enable: true
  appid: DPbkCJeWoLr90TX6j8gWpMmL-9Nh9j0Va # Your leancloud application appid
  appkey: IGgrmyUczpU4qob3MddLQca0 # Your leancloud application appkey
  visitor: true

github_banner:
  enable: true
  permalink: https://github.com/SunDoge


menu:
  home: / || fa fa-home
  #about: /about/ || fa fa-user
  tags: /tags/ || fa fa-tags
  categories: /categories/ || fa fa-th
  archives: /archives/ || fa fa-archive
  #schedule: /schedule/ || fa fa-calendar
  #sitemap: /sitemap.xml || fa fa-sitemap
  #commonweal: /404/ || fa fa-heartbeat

# Set the text alignment in the posts.
text_align:
  # Available values: start | end | left | right | center | justify | justify-all | match-parent
  desktop: left
  mobile: left
