scheme: Mist

valine:
  enable: true
  appid: DPbkCJeWoLr90TX6j8gWpMmL-9Nh9j0Va # Your leancloud application appid
  appkey: IGgrmyUczpU4qob3MddLQca0 # Your leancloud application appkey

github_banner:
  enable: true
  permalink: https://github.com/SunDoge